# Generated by Django 2.2.4 on 2019-08-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackOystercatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird_id', models.CharField(max_length=100)),
                ('bird_location', models.CharField(max_length=200)),
                ('general_location', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('sex', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('tarsus_length', models.FloatField()),
                ('body_length', models.FloatField()),
                ('head_length', models.FloatField()),
                ('head_width', models.FloatField()),
                ('head_height', models.FloatField()),
                ('culmen_length', models.FloatField()),
                ('culmen_height', models.FloatField()),
                ('culmen_width', models.FloatField()),
                ('bill_tip_height', models.FloatField()),
                ('bill_1cm_height', models.FloatField()),
                ('bill_2cm_height', models.FloatField()),
                ('bill_3cm_height', models.FloatField()),
                ('bill_4cm_height', models.FloatField()),
                ('bill_tip_width', models.FloatField()),
                ('bill_1cm_width', models.FloatField()),
                ('bill_2cm_width', models.FloatField()),
                ('bill_3cm_width', models.FloatField()),
                ('bill_4cm_width', models.FloatField()),
            ],
        ),
    ]
